//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.DataAccessLayer.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndustryCategory
    {
        public IndustryCategory()
        {
            this.CustomerDetails = new HashSet<CustomerDetail>();
        }
    
        public int IndustryCategoryId { get; set; }
        public string IndustryCategoryName { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<CustomerDetail> CustomerDetails { get; set; }
    }
}
